#!/usr/bin/env node
/* Generates static content pages, sitemap, robots, ads.txt and config.js from site.config.json.
   Usage: edit site.config.json, then run `node build.js`. No dependencies. */
const fs = require('fs'), path = require('path');
const ROOT = __dirname;
const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, 'site.config.json'), 'utf8'));
const warn = m => console.log('WARNING: ' + m);

const siteUrl = (cfg.siteUrl || '').replace(/\/$/, '');
if (!siteUrl) warn('siteUrl is empty: sitemap/canonical/og URLs use https://example.com');
if (!cfg.contactEmail) warn('contactEmail is empty: the Contact page shows a placeholder. Set a real address before applying to AdSense.');
if (cfg.adsenseClient && !/^ca-pub-\d{10,}$/.test(cfg.adsenseClient)) warn('adsenseClient should look like ca-pub-1234567890123456');
const base = siteUrl || 'https://example.com';
const email = cfg.contactEmail || 'contact@example.com';
const today = new Date().toISOString().slice(0, 10);
const LANGS = ['en', 'ko', 'th', 'vi', 'id'].map(c => require('./content/' + c + '.js'));
const SLUGS = ['guides', 'guide-korean-names', 'guide-five-elements', 'guide-korean-zodiac', 'guide-korean-surnames', 'guide-name-meanings', 'guide-zodiac-traits', 'about', 'privacy', 'terms', 'contact'];
const ADS_PAGES = new Set(SLUGS.filter(s => s.startsWith('guide-')));

// merge extra guide pages (content/x-<lang>.js) into each language
const H = require('./content/shared.js');
for (const L of LANGS) {
  const x = require('./content/x-' + L.code + '.js')(H);
  Object.assign(L.pages, x.pages);
  L.pages.guides.html = L.pages.guides.html.replace('</ul>', x.items + '\n</ul>');
}
const esc = s => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

const adsHead = cfg.adsenseClient
  ? `<meta name="google-adsense-account" content="${cfg.adsenseClient}">\n<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${cfg.adsenseClient}" crossorigin="anonymous"></script>`
  : '';

function page(L, slug) {
  const p = L.pages[slug];
  const u = L.ui;
  let html = p.html.replace(/\{\{EMAIL\}\}/g, email);
  if (ADS_PAGES.has(slug)) {
    html = html.replace('</p>', '</p>\n<div class="ad-slot" data-slot="article"></div>');
    html += '\n<div class="ad-slot" data-slot="article"></div>';
  }
  const nav = Object.entries(u.nav).map(([k, t]) => `<a href="${k === 'guides' ? 'guides' : k}.html">${esc(t)}</a>`).join(' · ');
  const url = `${base}/${L.code}/${slug}.html`;
  const showDate = ['privacy', 'terms', 'about', 'contact'].includes(slug) || slug.startsWith('guide-');
  return `<!doctype html>
<html lang="${L.htmlLang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(p.title)} | ${esc(u.siteName)}</title>
<meta name="description" content="${esc(p.desc)}">
<link rel="canonical" href="${url}">
${LANGS.map(x => `<link rel="alternate" hreflang="${x.htmlLang}" href="${base}/${x.code}/${slug}.html">`).join('\n')}
<meta property="og:type" content="article">
<meta property="og:title" content="${esc(p.title)}">
<meta property="og:description" content="${esc(p.desc)}">
<meta property="og:url" content="${url}">
<meta property="og:image" content="${base}/og.png">
<meta name="twitter:card" content="summary_large_image">
${adsHead}
<link rel="stylesheet" href="../style.css">
</head>
<body>
<div class="wrap page">
  <header>
    <div><a class="brand" href="../index.html?lang=${L.code}">${esc(u.siteName)}</a><p class="sub">${esc(u.tagline)}</p></div>
    <nav class="langs" aria-label="Language">${LANGS.map(x => `<a class="pill" href="../${x.code}/${slug}.html" hreflang="${x.htmlLang}"${x.code === L.code ? ' aria-current="page"' : ''}>${esc(x.otherLabel)}</a>`).join('')}</nav>
  </header>
  <nav class="links topnav">${nav}</nav>
  <article class="card prose">
    <h1>${esc(p.title)}</h1>
    ${html}
    ${slug.startsWith('guide-') ? `<p class="cta"><a class="go" href="../index.html?lang=${L.code}&amp;tab=name">${esc(u.cta)}</a> <a class="go alt" href="../index.html?lang=${L.code}&amp;tab=match">${esc(u.ctaMatch)}</a></p>` : ''}
    ${showDate ? `<p class="note">${esc(u.updated)}: ${today}</p>` : ''}
  </article>
  <nav class="links">${nav}</nav>
  <footer>© ${new Date().getFullYear()} ${esc(u.siteName)}. ${esc(u.rights)}</footer>
</div>
<script src="../config.js"></script>
<script src="../ads.js" defer></script>
</body>
</html>
`;
}

for (const L of LANGS) {
  fs.mkdirSync(path.join(ROOT, L.code), { recursive: true });
  for (const slug of SLUGS) fs.writeFileSync(path.join(ROOT, L.code, slug + '.html'), page(L, slug));
}

fs.writeFileSync(path.join(ROOT, 'config.js'),
  '/* Generated by build.js from site.config.json: edit that file, then run `node build.js` */\n' +
  'window.SITE_CONFIG = ' + JSON.stringify({ siteUrl, adsenseClient: cfg.adsenseClient || '', slots: cfg.slots || {} }) + ';\n');

const urls = [`${base}/`, ...LANGS.flatMap(L => SLUGS.map(s => `${base}/${L.code}/${s}.html`))];
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'),
  '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  urls.map(u => `  <url><loc>${u}</loc><lastmod>${today}</lastmod></url>`).join('\n') + '\n</urlset>\n');
fs.writeFileSync(path.join(ROOT, 'robots.txt'), `User-agent: *\nAllow: /\n\nSitemap: ${base}/sitemap.xml\n`);
fs.writeFileSync(path.join(ROOT, 'ads.txt'), cfg.adsenseClient
  ? `google.com, ${cfg.adsenseClient.replace('ca-', '')}, DIRECT, f08c47fec0942fa0\n`
  : '# Set adsenseClient in site.config.json and run `node build.js` to generate this file.\n');

// patch index.html head (between BUILD markers)
const idxPath = path.join(ROOT, 'index.html');
let idx = fs.readFileSync(idxPath, 'utf8');
const en = LANGS[0];
const head = [
  `<link rel="canonical" href="${base}/">`,
  `<meta property="og:type" content="website">`,
  `<meta property="og:title" content="${esc(en.ui.siteName)}: ${esc(en.ui.tagline)}">`,
  `<meta property="og:description" content="Get a fun Korean name with its meaning and check your K-Match. Share the card on Instagram and Facebook.">`,
  `<meta property="og:url" content="${base}/">`,
  `<meta property="og:image" content="${base}/og.png">`,
  `<meta name="twitter:card" content="summary_large_image">`,
  adsHead
].filter(Boolean).join('\n');
idx = idx.replace(/<!--BUILD:HEAD-->[\s\S]*?<!--BUILD:END-->/, `<!--BUILD:HEAD-->\n${head}\n<!--BUILD:END-->`);
fs.writeFileSync(idxPath, idx);
console.log(`Built ${LANGS.length * SLUGS.length} pages, sitemap.xml, robots.txt, ads.txt, config.js`);
